### ISSUE TITLE
Support user supplied sensitivity curve (wavelength)

### ISSUE THREAD

**Issue by cylammarco** [cylammarco/ASPIRED#18]
This is necessary if the service does not provide standards but only the sensitivity curve( as a function of wavelength).

**Comment by rjs3273** [comment]
Is there some official method in here for users to upvote enhancements? This is something I need and was just about to start looking into how to do it. If there were a supported method included in ASPIRED that would be very helpful.

**Comment by cylammarco** [comment]
This is implemented but not well tested, hence this issue remains open for now:

https://github.com/cylammarco/ASPIRED/blob/dev/aspired/spectral_reduction.py#L3774

**Comment by cylammarco** [comment]
> Is there some official method in here for users to upvote enhancements?

People usually use the thumb up or eyes emoji on the relevant message for that purpose.

**Comment by rjs3273** [comment]
Thanks. I am slowly working towards testing it. I will let you know how it goes.

**Comment by cylammarco** [comment]
This is possible with `add_sensitivity_itp`.
