### ISSUE TITLE
Calls to ap_trace_quick fail if plotly orca is not installed

### ISSUE THREAD

**Issue by jveitchmichaelis** [cylammarco/ASPIRED#2]
As title - fix is: 

```
conda install -c plotly plotly-orca
```

But probably an import somewhere it shouldn't be :)

**Comment by cylammarco** [comment]
Note: ap_trace_iraf is now ap_trace_quick

**Comment by cylammarco** [comment]
ap_trace() is reliable and fast enough, ap_trace_quick() is removed in 514d114.
