### ISSUE TITLE
Descriptive labels in FITS extensions

### ISSUE THREAD

**Issue by rjs3273** [cylammarco/ASPIRED#21]
The final output FITS from OneDSpec.savefits() can have up to about 15 extensions. I am struggling to tell them all apart and what is in each. Could description labels be added to each FITS header? 

If I use 
  OneDsSpec.save_fits(output='flux_resampled') 
then I get four HDUs. Three are labelled "flux" and one is labeled "sensitivity". When I add more options into the output='' string then I get no labels at all. The headers at the moment  are extremely sparse and I assume that is a work in progress.

**Comment by cylammarco** [comment]
Some progress is made to improve the flexibility in handling the header, it is now (in the dev-fits branch) possible to do that with some rather long and ugly syntax. More design and development on the API is needed to enable easier header handling.

**Comment by cylammarco** [comment]
The default header information is well populated now. However, I still need to go through more design/development plan before I can make this saving option more flexible. I am hoping it doesn't require fundamental structural change...

**Comment by cylammarco** [comment]
The FITS header is slightly more descriptive now. Closing this.

Further enhancement in populating the FITS header should refer to #23, which is an ongoing process.
