### ISSUE TITLE
Install without the test data

### ISSUE THREAD

**Issue by rjs3273** [cylammarco/ASPIRED#24]
I appreciate this is probably an administrative headache to reorganise the repository, but is there some easy mechanism by which I can install updates without having to pull the many Mb of test data? I am using
  pip install git+https://github.com/cylammarco/ASPIRED@dev
and it takes about 15min. I know it would also be possible to clone the repository once and pull updates, but you previously suggested that the pip install was the safer option until the other setup.py issues get cleaned up. Basically, does this require reorganising the repository or is there some pip magic I can use from my end to save myself downloading all those FITS? 15min is not the end of the world, so this is not a huge issue. Feel free to say I just have to live with it for the time being!

**Comment by cylammarco** [comment]
The examples are moved to https://github.com/cylammarco/ASPIRED-example.

The `git+` clones the entire repository, which is the cause of the slow process. You can speed it up by installing with `pip install https://github.com/cylammarco/ASPIRED/archive/dev.zip` which takes under a minute for me. When aspired is released properly at [PyPI](https://pypi.org/project/aspired/), there will be a significant performance improvement in the installation.

**Comment by cylammarco** [comment]
Just cleaned with [bfg-repo-cleaner](https://rtyley.github.io/bfg-repo-cleaner/); all .ipynb, .fit, .fits and .gz files and one of a documentation source file were removed. Now, a clone should only download ~30MB instead of ~360MB.

**Comment by rjs3273** [comment]
Brilliant. Thanks. I just tried it and it was a lot easier.
