### ISSUE TITLE
OneDSpec save fits/csv does not accept 'wavelength' as an output option.

### ISSUE THREAD

**Issue by P-R-McWhirter** [cylammarco/ASPIRED#39]
When calling the save_fits or save_csv routines of a OneDSpec object, requesting a wavelength output is not fulfilled. Additionally, this blocks the return of any other output option (flux, count, trace, etc.).

**Comment by cylammarco** [comment]
@P-R-McWhirter Did you get the warning: `wavelength ImageHDU cannot be created.` ? What is the error message, or does it just go through returning `None`?

**Comment by cylammarco** [comment]
Managed to replicate the results, will be fixed in the dev branch in the next commit. The `main` branch is planned to be patched in the second week of December.
