### ISSUE TITLE
Optimal extraction for curved spectra

### ISSUE THREAD

**Issue by cylammarco** [cylammarco/ASPIRED#44]
See [Marsh 1989](https://ui.adsabs.harvard.edu/abs/1989PASP..101.1032M/abstract).

**Comment by cylammarco** [comment]
Marsh algorithm only works on highly tilted spectra, not curved spectra.

See [Nicolai et al. 2020](https://ui.adsabs.harvard.edu/abs/2021A%26A...646A..32P/abstract) for an algorithm that can cope with highly curved Echelle spectra.

https://github.com/AWehrhahn/PyReduce/

**Comment by rjs3273** [comment]
That's interesting. You are just going to tell me to read the paper, but what's the problem with the Marsh algorithm? Without having tried it, in my mind I imagined that because the Marsh algorithm works across the chip pixel by pixel, locally, at the pixel being processed, a curved or tilted spectrum were the same thing. As long as the radius of curvature is very much more than one pixel, why are tilted and curved different? I guess I can see the sky getting more complicated.

**Comment by cylammarco** [comment]
Precisely, the sky modelling is getting complicated. A highly-tilted spectrum is only distorted in one axis direction, while in practice, spectra are usually distorted in both axis directions. Without considering the distortion in the other direction, the uncorrected curvature can lead to bad sky subtraction. All these are obvious but difficult to quantify... so I tried it with a FLOYDS spectrum, and it doesn't work well..: 
![image](https://user-images.githubusercontent.com/2545839/109406006-48412080-797e-11eb-830d-0cb4d28155c7.png)

This figure illustrates how the subsmapling has to handle both x and y direction simultaneously in order to perform extraction properly without resampling:

![image](https://user-images.githubusercontent.com/2545839/109405910-812cc580-797d-11eb-9609-80475ece6c35.png)
(from https://www.aanda.org/articles/aa/full_html/2021/02/aa38293-20/F7.html)

**Comment by cylammarco** [comment]
Including the PyPI latest version of pyreduce-astro  as a dependency (see also https://github.com/AWehrhahn/PyReduce). This is the official software developed by the authors in that paper. This will be available in the next release.

**Comment by cylammarco** [comment]
The dependence on PyReduce is removed due to the requirement of an indepedent sky spectrum for sky subtraction. An image rectification process is added instead.
