### ISSUE TITLE
Typo in the installation instructions

### ISSUE THREAD

**Issue by rjs3273** [cylammarco/ASPIRED#56]
It's a pretty trivial typo, but being in the "how to install" instructions, it is going to cause confusion. If I didn't happen to know your real name it would probably have had me stumped for rather longer.

On
  https://aspired.readthedocs.io/en/latest/installation/pip.html 
you have
  https://github.com/cyalmmarco/ASPIRED.git
instead of 
  https://github.com/cylammarco/ASPIRED.git

**Comment by cylammarco** [comment]
It will be updated in the next iteration of documentation writing, expected to happen this week.

**Comment by cylammarco** [comment]
Fixed. Require a force refresh to view the updated page.
