### ISSUE TITLE
unexpected keyword argument 'logger_name'

### ISSUE THREAD

**Issue by rjs3273** [cylammarco/ASPIRED#60]
Hi Marco. I have been trying to get bring my aspired scripts up the latest release version. I believe I have sorted out the methods that got moved from the onedspec class to the twodspec class, so that's OK. I now get

target1D.initialise_calibrator()

~/miniconda3/envs/astroconda/lib/python3.6/site-packages/aspired/onedspec.py in initialise_calibrator(self, spec_id, peaks, arc_spec, stype)
   1587                     self.science_wavecal[i].initialise_calibrator(
   1588                         peaks=peaks, arc_spec=arc_spec)
-> 1589                     self.science_wavecal[i].set_calibrator_properties()
   1590                     self.science_wavecal[i].set_hough_properties()
   1591                     self.science_wavecal[i].set_ransac_properties()

~/miniconda3/envs/astroconda/lib/python3.6/site-packages/aspired/wavelength_calibration.py in set_calibrator_properties(self, num_pix, pixel_list, plotting_library, logger_name, log_level)
    523             plotting_library=plotting_library,
    524             logger_name=logger_name,
--> 525             log_level=log_level)
    526 
    527         self.spectrum1D.add_calibrator_properties(

TypeError: set_calibrator_properties() got an unexpected keyword argument 'logger_name'

I suspect I just have the wrong version of the libraries again. You did try to explain all the "Branches" and "Tags" in github to me, but I never really understood! I have tried installing both the Main and dev branches but get this same "unexpected keyword argument" error.

Install using pip from github
  pip install git+https://github.com/cylammarco/ASPIRED.git@dev
  pip install git+https://github.com/cylammarco/ASPIRED.git@main

**Comment by cylammarco** [comment]
@rjs3273, I suspect it may be coming from rascal, see if this works:

```
pip uninstall rascal
pip install git+https://github.com/jveitchmichaelis/rascal.git@dev
```

**Comment by rjs3273** [comment]
Yes. Brilliant. I think I knew that but got bogged down in ASPIRED versions and completely forgot to update the RASCAL stuff. 

Thanks.
