### ISSUE TITLE
'Calibrator' object has no attribute 'add_user_atlas'

### ISSUE THREAD

**Issue by rjs3273** [cylammarco/ASPIRED#63]
I had this error before and I think you fixed it by telling me to update rascal. 

```
target1D = spectral_reduction.OneDSpec()
target1D.from_twodspec(target2D, stype='science')    
atlas = [4501.0, 4524.7, 4582.8, 4624.28, 4671.23, 4807.02, 7802.65, 7887.40, 7967.34]
element = ['Xe'] * len(atlas)
target1D.add_user_atlas(elements=element, wavelengths=atlas, stype='science')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-fc68e5f68e2b> in <module>
     22 element = ['Xe'] * len(atlas)
     23 
---> 24 target1D.add_user_atlas(elements=element, wavelengths=atlas, stype='science')

~/miniconda3/envs/astroconda/lib/python3.6/site-packages/aspired/onedspec.py in add_user_atlas(self, elements, wavelengths, spec_id, intensities, candidate_tolerance, constrain_poly, vacuum, pressure, temperature, relative_humidity, stype)
   2108                     pressure=pressure,
   2109                     temperature=temperature,
-> 2110                     relative_humidity=relative_humidity)
   2111                 self.logger.info(
   2112                     'Added user supplied atlas to '

~/miniconda3/envs/astroconda/lib/python3.6/site-packages/aspired/wavelength_calibration.py in add_user_atlas(self, elements, wavelengths, intensities, candidate_tolerance, constrain_poly, vacuum, pressure, temperature, relative_humidity)
    735         '''
    736 
--> 737         self.spectrum1D.calibrator.add_user_atlas(
    738             elements=elements,
    739             wavelengths=wavelengths,

AttributeError: 'Calibrator' object has no attribute 'add_user_atlas'

```

I have uninstalled and reinstalled the @dev branch of rascal and still getting this error.

**Comment by cylammarco** [comment]
I believe @jveitchmichaelis deleted the entire function by mistake in the dev... 

@rjs3273 Please use `pip install rascal`. The v0.3 should work.

**Comment by jveitchmichaelis** [comment]
If you're running on rascal:dev, I moved this functionality to the Atlas
class - you need to make an Atlas object and add the user lines to it (see
examples)

**Comment by cylammarco** [comment]
@jveitchmichaelis This is much more commonly used than the `add_atlas()` function, I think we should have it available in the top level API.

**Comment by cylammarco** [comment]
@rjs3273 Please see
https://github.com/jveitchmichaelis/rascal/blob/dev/examples/example_lt_sprat_xe.py#L40-L50

for the new atlas setting for the future v0.4 release.

Or use `pip install rascal` for v0.3.

@jveitchmichaelis Is there a timeline for the v0.4?

**Comment by jveitchmichaelis** [comment]
as in a method for `Calibrator`? or within `Atlas`?

**Comment by jveitchmichaelis** [comment]
Hmm we could add a legacy option to the dev api and let's assume we'll phase it out for 0.4.0?

**Comment by cylammarco** [comment]
OK

**Comment by rjs3273** [comment]
Thanks, chaps. I can confirm I am running fine with rascal v.0.3 installed.
In the longer run, should I stop using aspired.OneDSpec.add_user_atlas() or is it staying?

**Comment by cylammarco** [comment]
It is possible for aspired to support it indefinitely, and I think that should be the case. I will have a closer look when rascal v0.4 and its future plan has become clearer.
