### ISSUE TITLE
ImageReduction specification input list requires arc

### ISSUE THREAD

**Issue by rjs3273** [cylammarco/ASPIRED#7]
It appears to be mandatory that the text list file passed to ImageReduction() includes an arc, but it is not tested and trapped if missing. I wanted to use the tracing and extraction routines without doing a wavelength calibration so I did not include an arc and got the following error.

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-67d999ce62e3> in <module>
----> 1 science_frame = aspired.ImageReduction('RJSTest/v_e_20160808_20_1_0_1.list');

/data/LT/Commissioning/SPRAT/Aspired/ASPIRED/aspired/aspired.py in __init__(self, filelistpath, ftype, saxis, saxis_keyword, combinetype_light, sigma_clipping_light, clip_low_light, clip_high_light, exptime_light, exptime_light_keyword, combinetype_dark, sigma_clipping_dark, clip_low_dark, clip_high_dark, exptime_dark, exptime_dark_keyword, combinetype_bias, sigma_clipping_bias, clip_low_bias, clip_high_bias, combinetype_flat, sigma_clipping_flat, clip_low_flat, clip_high_flat, silence)
    239                                       dtype='str',
    240                                       autostrip=True)
--> 241         self.imtype = self.filelist[:, 0]
    242         self.impath = self.filelist[:, 1]
    243         try:

IndexError: too many indices for array
---------------------------------------------------------------------------

After adding an arc line to the text file with a dummy file name assigned to "arc" that I will never use it works OK.

**Comment by cylammarco** [comment]
I believe that bug is actually two bugs:
(1) The ImageReduction.init() cannot handle filelist containing only 1 line
(2) "Missing" arc file(s) is not trapped
