### ISSUE TITLE
Keyword LABEL fits header

### ISSUE THREAD

**Issue by bschneider-astro** [cylammarco/ASPIRED#77]
Hi @cylammarco, thank you for this amazing and user friendly tool you have developed to reduce spectral data. 
I noticed that the **LABEL** keyword in the header of the fits created by the _save_fits_ function with the **output='flux'** option of (at least) _OneDSpec_ is the same for the three HDU images. It seems to be the same when I use **output='count_resampled+flux_resampled'** . To analyze the reduced and calibrated spectrum, I would need to have a unique ID for each HDU image to automatically find and open the right image in the script. Another possibility would be to add a name to each extension instead of "NoName". Please let me know if anything can be done. Thanks, Benjamin. 

<img width="1742" alt="Screenshot 2022-03-25 at 15 12 01" src="https://user-images.githubusercontent.com/67140982/160137773-0b639299-0573-4aba-a5d8-479c67e5ef1d.png">

**Comment by cylammarco** [comment]
Hi @bschneider-astro, thank you for using aspired and reporting the bug. Would you please try the fix at the main branch and see if it fixes your problem? The EXTNAME and LABEL for each HDU are now unique and the pairs are identical. If that works, I can turn this into a patch release.

**Comment by bschneider-astro** [comment]
I tested with the main branch and now the EXTNAME and LABEL of the fits file are perfect. Thanks for the quick fix!
<img width="777" alt="Screenshot 2022-03-25 at 17 01 22" src="https://user-images.githubusercontent.com/67140982/160157225-7e25b9d4-3741-4673-a45f-a00bf006bac4.png">
