### ISSUE TITLE
Typo in _bias_subtract function

### ISSUE THREAD

**Issue by bschneider-astro** [cylammarco/ASPIRED#79]
Hi @cylammarco, I found a small bug during the image reduction process. There is a typo in the name **light_reduced** in __bias_subtract_ function that it is written as **light_redcued**. This means that the bias is never subtracted. There is also the same typo in the  __flatfield_ function.

<img width="986" alt="Screenshot 2022-03-25 at 22 03 34" src="https://user-images.githubusercontent.com/67140982/160200453-39d83be7-daf1-46dd-8fe9-f091611f396c.png">

**Comment by cylammarco** [comment]
This is now fixed in the dev-0.4.X, dev and main, but I fear there are more typos of this kind of I will keep this open for the time being and a patch will be released when we are more certain there are not more simple typo bugs like this.

**Comment by cylammarco** [comment]
Fixed in v0.4.4. Keep open for now as more typo checking will be needed.
