### ISSUE TITLE
Can save_fits() write out spectra that are not yet flux calibrated?

### ISSUE THREAD

**Issue by rjs3273** [cylammarco/ASPIRED#8]
save_fits() calls _create_fits() which assumes the flux calibration has already been applied. I believe users will frequently want to save off the spectrum at various stages along the reduction. In particular it will be extremely common for observers to extract and wavelength calibrate an observation but not have a standard available. Even if they do intend to flux calibrate, they may simply have observed the target before the standard.

**Comment by cylammarco** [comment]
The current plan is to divide the entire FITS saving into 6 parts:
(1) Reduced image (ImageReduction)
(2) Trace (TwoDSpec)
(3) Extracted ADU + Uncertainties + Sky (TwoDSpec)
(4) Polyfit coefficient (WavelengthPolyFit)
(5) Resampled wavelength calibrated ADU + Uncertainties + Sky (OneDSpec)
(6) Wavelength and Flux calibrated spectrum + Sensitivity Curve (OneDSpec)
(6b) Resampled wavelength and Flux calibrated spectrum + Sensitivity Curve (OneDSpec)
*(7) Any combination of them
** **Resampled** meaning it's readable by iraf splot

ImageHDU can be converted to PrimaryHDU by
```
if isinstance(hdu, ImageHDU):
    hdu = PrimaryHDU(hdu.data, hdu.header)
```
meaning everything can be stored as ImagHDU at the first place, the key ImageHDU (e.g. spectrum) can be converted to a PrimaryHDU before saving to file.

The default output of a full reduction contains (4), (6) and (6b), which contains sufficient information to reconstruct (3), (5).

Items (3) and (5) are only different in the header, as (5) is wavelength calibrated.

**Comment by cylammarco** [comment]
save_fits() can perform the above now, it is no longer blocking. More enhancement will be added before beta release, so keep this open.

**Comment by cylammarco** [comment]
@rjs3273 any wish-list?

**Comment by cylammarco** [comment]
Further enhanced in https://github.com/cylammarco/ASPIRED/commit/554ba020c5502b9bd2ca90d44ace489963da0f6b

Will be an ongoing enhancement for future work. But the software is certainly supporting this feature. Please open new issues for specific bug and feature requests.
